apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-staging
resources:
  - ../../base
images:
  - name: ghcr.io/vojtechmares/js-on-k8s-example
    newTag: main
configMapGenerator:
  - name: app
    behavior: merge
    literals:
      - LOG_LEVEL=debug
