image:
  repository: ghcr.io/vojtechmares/js-on-k8s-example
  tag: ""  # defaults to Chart.appVersion
replicaCount: 2
port: 3000
resources:
  requests:
    cpu: "1"
    memory: 256Mi
  limits:
    memory: 256Mi
env:
  LOG_LEVEL: info
  GREETING: hello
  NODE_OPTIONS: "--max-old-space-size=192"
